# Generated by Django 3.2.14 on 2022-11-24 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Architects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('images', models.ImageField(upload_to='photos/architects')),
                ('descript', models.TextField(max_length=1000)),
                ('email', models.EmailField(max_length=254)),
                ('office_add', models.TextField(max_length=1000)),
            ],
        ),
    ]
